   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: personal-portfolio
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: personal-portfolio
     template:
       metadata:
         labels:
           app: personal-portfolio
       spec:
         containers:
         - name: personal-portfolio
           image: us-west1-docker.pkg.dev/personal-portfolio-421722/personalportfolio/rp-portfolio-web
           ports:
           - containerPort: 8000