   apiVersion: v1
   kind: Service
   metadata:
     name: personal-portfolio
   spec:
     type: LoadBalancer
     ports:
     - port: 8000
       targetPort: 8000
     selector:
       app: personal-portfolio